.TH "C:/workspace/Computer Vision/OpenCVTest Directory Reference" 3 "Tue Jan 4 2022" "Version 0.1" "Computer Vision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Computer Vision/OpenCVTest Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMetric\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMetric\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCVTest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProcessImages\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProcessImages\&.h\fP"
.br
.in -1c
