.TH "C:/workspace/Computer Vision/OpenCVProjekt/OpenCVTest Directory Reference" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Computer Vision/OpenCVProjekt/OpenCVTest Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMetric\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMetric\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCVTest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProcessImages\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProcessImages\&.h\fP"
.br
.in -1c
