.TH "coords" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coords
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Metric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float coords::x"

.SS "float coords::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
