.TH "f_conv_context" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_conv_context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBbuf\fP"
.br
.ti -1c
.RI "   wchar_t * \fBwbuf\fP"
.br
.ti -1c
.RI "   const void * \fBu8str\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "size_t \fBraw_avail\fP"
.br
.ti -1c
.RI "struct \fBf_context\fP * \fBcntx\fP"
.br
.ti -1c
.RI "enum \fBf_string_type\fP \fBb_type\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "enum \fBf_string_type\fP f_conv_context::b_type"

.SS "char* f_conv_context::buf"

.SS "struct \fBf_context\fP* f_conv_context::cntx"

.SS "size_t f_conv_context::raw_avail"

.SS "union  { \&.\&.\&. }  f_conv_context::u"

.SS "const void* f_conv_context::u8str"

.SS "wchar_t* f_conv_context::wbuf"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
