.TH "f_context" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBf_table_properties_t\fP * \fBtable_properties\fP"
.br
.ti -1c
.RI "size_t \fBrow\fP"
.br
.ti -1c
.RI "size_t \fBcolumn\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t f_context::column"

.SS "size_t f_context::row"

.SS "\fBf_table_properties_t\fP* f_context::table_properties"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
