.TH "f_row" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_row
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBf_vector_t\fP * \fBcells\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBf_vector_t\fP* f_row::cells"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
