.TH "f_table_properties" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_table_properties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBfort_border_style\fP \fBborder_style\fP"
.br
.ti -1c
.RI "\fBf_cell_prop_container_t\fP * \fBcell_properties\fP"
.br
.ti -1c
.RI "\fBfort_entire_table_properties_t\fP \fBentire_table_properties\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBfort_border_style\fP f_table_properties::border_style"

.SS "\fBf_cell_prop_container_t\fP* f_table_properties::cell_properties"

.SS "\fBfort_entire_table_properties_t\fP f_table_properties::entire_table_properties"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
