.TH "fort::table< TT >::default_properties" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort::table< TT >::default_properties
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.hpp>\fP
.PP
Inherits \fBfort::property_owner< table >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdefault_properties\fP (\fBtable\fP *tbl)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> \fBfort::table\fP< TT >::default_properties::default_properties (\fBtable\fP * tbl)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
