.TH "fort_entire_table_properties" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort_entire_table_properties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBleft_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBtop_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBright_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBbottom_margin\fP"
.br
.ti -1c
.RI "enum \fBft_adding_strategy\fP \fBadd_strategy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "enum \fBft_adding_strategy\fP fort_entire_table_properties::add_strategy"

.SS "unsigned int fort_entire_table_properties::bottom_margin"

.SS "unsigned int fort_entire_table_properties::left_margin"

.SS "unsigned int fort_entire_table_properties::right_margin"

.SS "unsigned int fort_entire_table_properties::top_margin"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
