.TH "fort::table< TT >::cell_range" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort::table< TT >::cell_range
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.hpp>\fP
.PP
Inherits \fBfort::property_owner< table >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcell_range\fP (size_t top_left_row, size_t top_left_col, size_t bottom_right_row, size_t bottom_right_col, \fBtable\fP &tbl)"
.br
.ti -1c
.RI "void \fBerase\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<\fBtable_type\fP TT = table_type::character>
.br
class fort::table< TT >::cell_range"Range of cells\&.
.PP
\fBNote\fP
.RS 4
: at the moment function of propery owener will work only on the top left cell\&. 
.RE
.PP
\fBTodo\fP
.RS 4
: Implement their work on the whole range\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> \fBfort::table\fP< TT >::cell_range::cell_range (size_t top_left_row, size_t top_left_col, size_t bottom_right_row, size_t bottom_right_col, \fBtable\fP & tbl)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> void \fBfort::table\fP< TT >::cell_range::erase ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
