.TH "fort::detail" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort::detail
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > constexpr bool \fBis_stream_manipulator_impl\fP () noexcept"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > constexpr bool fort::detail::is_stream_manipulator_impl ()\fC [constexpr]\fP, \fC [noexcept]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
