.TH "fort::table< TT >::table_column" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort::table< TT >::table_column
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.hpp>\fP
.PP
Inherits \fBfort::property_owner< table >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtable_column\fP (std::size_t col_idx, \fBtable\fP &tbl)"
.br
.ti -1c
.RI "void \fBerase\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<\fBtable_type\fP TT = table_type::character>
.br
class fort::table< TT >::table_column"Table column\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> \fBfort::table\fP< TT >::table_column::table_column (std::size_t col_idx, \fBtable\fP & tbl)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> void \fBfort::table\fP< TT >::table_column::erase ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
