.TH "fort::table< TT >::table_row" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort::table< TT >::table_row
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.hpp>\fP
.PP
Inherits \fBfort::property_owner< table >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtable_row\fP (std::size_t row_idx, \fBtable\fP &tbl)"
.br
.ti -1c
.RI "class \fBtable_cell\fP \fBoperator[]\fP (std::size_t coll_idx)"
.br
.ti -1c
.RI "void \fBerase\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<\fBtable_type\fP TT = table_type::character>
.br
class fort::table< TT >::table_row"Table row\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> \fBfort::table\fP< TT >::table_row::table_row (std::size_t row_idx, \fBtable\fP & tbl)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtable_type\fP TT = table_type::character> void \fBfort::table\fP< TT >::table_row::erase ()\fC [inline]\fP"

.SS "template<\fBtable_type\fP TT = table_type::character> class \fBtable_cell\fP \fBfort::table\fP< TT >::table_row::operator[] (std::size_t coll_idx)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
