.TH "ft_border_chars" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_border_chars
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtop_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBseparator_ch\fP"
.br
.ti -1c
.RI "const char * \fBbottom_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBside_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBout_intersect_ch\fP"
.br
.ti -1c
.RI "const char * \fBin_intersect_ch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure describing border appearance\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* ft_border_chars::bottom_border_ch"

.SS "const char* ft_border_chars::in_intersect_ch"

.SS "const char* ft_border_chars::out_intersect_ch"

.SS "const char* ft_border_chars::separator_ch"

.SS "const char* ft_border_chars::side_border_ch"

.SS "const char* ft_border_chars::top_border_ch"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
