.TH "ft_border_style" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_border_style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBft_border_chars\fP \fBborder_chs\fP"
.br
.ti -1c
.RI "struct \fBft_border_chars\fP \fBheader_border_chs\fP"
.br
.ti -1c
.RI "const char * \fBhor_separator_char\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure describing border style\&. 
.SH "Member Data Documentation"
.PP 
.SS "struct \fBft_border_chars\fP ft_border_style::border_chs"

.SS "struct \fBft_border_chars\fP ft_border_style::header_border_chs"

.SS "const char* ft_border_style::hor_separator_char"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
