.TH "ft_table" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBf_vector_t\fP * \fBrows\fP"
.br
.ti -1c
.RI "\fBf_table_properties_t\fP * \fBproperties\fP"
.br
.ti -1c
.RI "\fBf_string_buffer_t\fP * \fBconv_buffer\fP"
.br
.ti -1c
.RI "size_t \fBcur_row\fP"
.br
.ti -1c
.RI "size_t \fBcur_col\fP"
.br
.ti -1c
.RI "\fBf_vector_t\fP * \fBseparators\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBf_string_buffer_t\fP* ft_table::conv_buffer"

.SS "size_t ft_table::cur_col"

.SS "size_t ft_table::cur_row"

.SS "\fBf_table_properties_t\fP* ft_table::properties"

.SS "\fBf_vector_t\fP* ft_table::rows"

.SS "\fBf_vector_t\fP* ft_table::separators"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
