.TH "interval" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interval
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBfirst\fP"
.br
.ti -1c
.RI "int32_t \fBlast\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int32_t interval::first"

.SS "int32_t interval::last"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
