.TH "label" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
label
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Metric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheigth\fP"
.br
.ti -1c
.RI "float \fBbrightness\fP"
.br
.ti -1c
.RI "int \fBnumberplateCount\fP"
.br
.ti -1c
.RI "std::vector< int > \fBcharacterCount\fP"
.br
.ti -1c
.RI "std::vector< \fBCoords\fP > \fBcoordinates\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float label::brightness"

.SS "std::vector<int> label::characterCount"

.SS "std::vector<\fBCoords\fP> label::coordinates"

.SS "float label::heigth"

.SS "int label::id"

.SS "int label::numberplateCount"

.SS "float label::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
