.TH "C:/workspace/Computer Vision/OpenCVProjekt/OpenCVTest/ProcessImages.h" 3 "Wed Jan 19 2022" "Version v1.0" "CV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Computer Vision/OpenCVProjekt/OpenCVTest/ProcessImages.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <opencv2/core/utils/logger\&.hpp>\fP
.br
\fC#include 'wtypes\&.h'\fP
.br
\fC#include 'Metric\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProcessImages\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBDARKNESS_THRESHOLD\fP = 100"
.br
.ti -1c
.RI "const float \fBWHITE_PIXEL_TRESHOLD_LOW\fP = 0\&.4700"
.br
.ti -1c
.RI "const float \fBWHITE_PIXEL_THRESHOLD_HIGH\fP = 0\&.800"
.br
.ti -1c
.RI "const float \fBASPECT_RATIO_MIN\fP = 1\&.9f"
.br
.ti -1c
.RI "const float \fBASPECT_RATIO_MAX\fP = 15\&.0f"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const float ASPECT_RATIO_MAX = 15\&.0f"

.SS "const float ASPECT_RATIO_MIN = 1\&.9f"

.SS "const int DARKNESS_THRESHOLD = 100"

.SS "const float WHITE_PIXEL_THRESHOLD_HIGH = 0\&.800"

.SS "const float WHITE_PIXEL_TRESHOLD_LOW = 0\&.4700"

.SH "Author"
.PP 
Generated automatically by Doxygen for CV from the source code\&.
